---
- name: install mongodb
  hosts: all
  become: true
  tasks:
    - name: install packages for app
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - mongodb
